const lessonTitle = "淘气的鞋";

const lessonData = [
    // ===== 第1段 =====
    ["“", "", "", ""],
    ["跟我", "gēn wǒ", "Follow me", "Ikut saya"],
    ["跟你", "gēn nǐ", "with you", "dengan awak"],
    ["一起去", "yì qǐ qù", "go together", "pergi bersama"],
    ["。”", "", "", ""],
    ["右脚的鞋", "yòu jiǎo de xié", "The right shoe", "Kasut kanan"],
    ["连忙", "lián máng", "hurriedly", "segera"],
    ["说", "shuō", "said", "berkata"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    ["它们俩", "tā men liǎ", "The two of them", "Mereka berdua"],
    ["从", "cóng", "from", "dari"],
    ["敞开的", "chǎng kāi de", "open", "yang terbuka"],
    ["窗户", "chuāng hu", "window", "tingkap"],
    ["爬了", "pá le", "crawled", "merangkak"],
    ["出去", "chū qù", "out", "keluar"],
    ["。", "", "", ""],
    ["床下", "chuáng xià", "Under the bed", "Di bawah katil"],
    ["、", "", "", ""],
    ["椅子下", "yǐ zi xià", "under the chairs", "di bawah kerusi"],
    ["的鞋子", "de xié zi", "shoes", "kasut-kasut"],
    ["有样学样", "yǒu yàng xué yàng", "followed suit", "ikut-ikutan"],
    ["，", "", "", ""],
    ["跟着", "gēn zhe", "followed", "mengikuti"],
    ["出走了", "chū zǒu le", "went out", "keluar"],
    ["，", "", "", ""],
    ["就连", "jiù lián", "even", "malahan"],
    ["柜子里", "guì zi lǐ", "in the cupboard", "dalam almari"],
    ["的鞋子", "de xié zi", "shoes", "kasut-kasut"],
    ["听见", "tīng jiàn", "heard", "mendengar"],
    ["动静后", "dòng jìng hòu", "the commotion", "keriuhan"],
    ["，", "", "", ""],
    ["也", "yě", "also", "juga"],
    ["合力", "hé lì", "together", "berganding tenaga"],
    ["把", "bǎ", "", ""],
    ["门", "mén", "door", "pintu"],
    ["撞开", "zhuàng kāi", "broke open", "langgar buka"],
    ["，", "", "", ""],
    ["一起", "yì qǐ", "together", "bersama"],
    ["加入", "jiā rù", "joined", "menyertai"],
    ["它们的行列", "tā men de háng liè", "their ranks", "barisan mereka"],
    ["，", "", "", ""],
    ["来到", "lái dào", "came to", "tiba di"],
    ["漆黑的", "qī hēi de", "dark", "gelap"],
    ["街上", "jiē shàng", "street", "jalan"],
    ["。", "", "", ""],
    ["邻居门前", "lín jū mén qián", "Neighbors' doorsteps", "Di hadapan rumah jiran"],
    ["的鞋子", "de xié zi", "shoes", "kasut-kasut"],
    ["看到", "kàn dào", "saw", "melihat"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["也", "yě", "also", "juga"],
    ["纷纷", "fēn fēn", "one after another", "satu demi satu"],
    ["跟了上来", "gēn le shàng lái", "followed", "mengikuti"],
    ["。", "", "", ""],
    ["于是", "yú shì", "So", "Maka"],
    ["，", "", "", ""],
    ["社区里", "shè qū lǐ", "in the neighborhood", "di kawasan perumahan"],
    ["所有的鞋", "suǒ yǒu de xié", "all the shoes", "semua kasut"],
    ["都", "dōu", "all", "semua"],
    ["聚拢在", "jù lǒng zài", "gathered on", "berkumpul di"],
    ["街上", "jiē shàng", "the street", "jalan"],
    ["，", "", "", ""],
    ["仿佛", "fǎng fú", "as if", "seolah-olah"],
    ["组成", "zǔ chéng", "forming", "membentuk"],
    ["了一支", "le yì zhī", "a", "sebuah"],
    ["声势浩大的", "shēng shì hào dà de", "mighty", "yang hebat"],
    ["巡逻队", "xún luó duì", "patrol team", "pasukan rondaan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    ["“", "", "", ""],
    ["你在哪儿", "nǐ zài nǎ r", "Where are you", "Awak di mana"],
    ["？”", "", "", ""],
    ["询问声", "xún wèn shēng", "Asking voices", "Suara pertanyaan"],
    ["在", "zài", "in", "di"],
    ["黑暗中", "hēi àn zhōng", "the darkness", "kegelapan"],
    ["响起", "xiǎng qǐ", "sounded", "berbunyi"],
    ["。", "", "", ""],
    ["“", "", "", ""],
    ["我在这儿", "wǒ zài zhè r", "I'm here", "Saya di sini"],
    ["！”", "", "", ""],
    ["回答声", "huí dá shēng", "Answering voices", "Suara jawapan"],
    ["从", "cóng", "from", "dari"],
    ["周围", "zhōu wéi", "all around", "sekeliling"],
    ["传来", "chuán lái", "came", "datang"],
    ["。", "", "", ""],
    ["谁和谁", "shuí hé shuí", "Which with which", "Siapa dengan siapa"],
    ["才是一对", "cái shì yí duì", "is a pair", "barulah sepasang"],
    ["？", "", "", ""],
    ["左脚鞋", "zuǒ jiǎo xié", "Left shoes", "Kasut kiri"],
    ["找到", "zhǎo dào", "found", "menemui"],
    ["右脚鞋后", "yòu jiǎo xié hòu", "the right shoes", "kasut kanan"],
    ["走在一起", "zǒu zài yī qǐ", "walked together", "berjalan bersama"],
    ["，", "", "", ""],
    ["有的", "yǒu de", "some", "sesetengah"],
    ["还用", "hái yòng", "even used", "malah menggunakan"],
    ["鞋带", "xié dài", "shoelaces", "tali kasut"],
    ["互相拴好", "hù xiāng shuān hǎo", "tied each other", "mengikat bersama"],
    ["，", "", "", ""],
    ["街上", "jiē shàng", "the street", "jalan"],
    ["闹哄哄的", "nào hōng hōng de", "noisy", "riuh-rendah"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    ["“", "", "", ""],
    ["别找了", "bié zhǎo le", "Stop looking", "Jangan cari"],
    ["！”", "", "", ""],
    ["有只鞋", "yǒu zhī xié", "A shoe", "Sehelai kasut"],
    ["大喊", "dà hǎn", "shouted", "berteriak"],
    ["，", "", "", ""],
    ["“", "", "", ""],
    ["从现在开始", "cóng xiàn zài kāi shǐ", "From now on", "Mulai sekarang"],
    ["，", "", "", ""],
    ["我们用不着配对", "wǒ men yòng bù zháo pèi duì", "we don't need to pair up", "kita tidak perlu berpasangan"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["每只鞋", "měi zhī xié", "Each shoe", "Setiap kasut"],
    ["各自独立", "gè zì dú lì", "independent", "berdiri sendiri"],
    ["。”", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    ["队伍", "duì wǔ", "The procession", "Perarakan"],
    ["继续", "jì xù", "continued", "terus"],
    ["向前", "xiàng qián", "forward", "ke hadapan"],
    ["走去", "zǒu qù", "walked", "berjalan"],
    ["，", "", "", ""],
    ["高贵的皮鞋", "gāo guì de pí xié", "Noble leather shoes", "Kasut kulit yang mulia"],
    ["争先恐后地", "zhēng xiān kǒng hòu de", "competing to be first", "berlumba-lumba"],
    ["踏过", "tà guò", "stepped through", "memijak"],
    ["水坑", "shuǐ kēng", "puddles", "lopak air"],
    ["；", "", "", ""],
    ["那些", "nà xiē", "those", "kasut-kasut"],
    ["又破又脏", "yòu pò yòu zāng", "old and dirty", "usang dan kotor"],
    ["的旧鞋", "de jiù xié", "old shoes", "lama"],
    ["则", "zé", "while", "manakala"],
    ["踮起鞋尖儿", "diǎn qǐ xié jiān r", "tiptoed", "menaikkan hujung kasut"],
    ["，", "", "", ""],
    ["小心翼翼地", "xiǎo xīn yì yì de", "cautiously", "dengan berhati-hati"],
    ["绕过", "rào guò", "went around", "memintas"],
    ["泥地", "ní dì", "muddy ground", "tanah berlumpur"],
    ["。", "", "", ""],
    ["老人的鞋", "lǎo rén de xié", "Old people's shoes", "Kasut orang tua"],
    ["又蹦又跳", "yòu bèng yòu tiào", "hopped and skipped", "melompat-lompat"],
    ["，", "", "", ""],
    ["孩子的鞋", "hái zi de xié", "Children's shoes", "Kasut kanak-kanak"],
    ["却", "què", "yet", "sebaliknya"],
    ["迈着", "mài zhe", "took", "melangkah"],
    ["迟缓而稳重", "chí huǎn ér wěn zhòng", "slow and steady", "perlahan dan stabil"],
    ["的", "de", "", ""],
    ["步子", "bù zi", "steps", "langkah"],
    ["。", "", "", ""],
    ["这些鞋", "zhè xiē xié", "These shoes", "Kasut-kasut ini"],
    ["终于", "zhōng yú", "finally", "akhirnya"],
    ["成为", "chéng wéi", "became", "menjadi"],
    ["自己的主人", "zì jǐ de zhǔ rén", "their own masters", "tuan diri sendiri"],
    ["，", "", "", ""],
    ["不再", "bù zài", "no longer", "tidak lagi"],
    ["受束缚", "shòu shù fù", "restrained", "terikat"],
    ["，", "", "", ""],
    ["纵情狂欢", "zòng qíng kuáng huān", "reveled", "bersuka ria"],
    ["了", "le", "", ""],
    ["一宿", "yì xiǔ", "all night", "sepanjang malam"],
    ["。", "", "", ""],
    ["瞬间", "shùn jiān", "Instantly", "Sekelip mata"],
    ["，", "", "", ""],
    ["太阳", "tài yáng", "the sun", "matahari"],
    ["露出脸来", "lù chū liǎn lái", "showed its face", "menunjukkan wajah"],
    ["，", "", "", ""],
    ["金色的", "jīn sè de", "golden", "keemasan"],
    ["光线", "guāng xiàn", "rays", "cahaya"],
    ["驱走了", "qū zǒu le", "drove away", "menghalau"],
    ["黑暗", "hēi àn", "darkness", "kegelapan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    ["“", "", "", ""],
    ["我们", "wǒ men", "We", "Kita"],
    ["得", "děi", "must", "mesti"],
    ["在", "zài", "before", "sebelum"],
    ["人们", "rén men", "people", "orang ramai"],
    ["起床", "qǐ chuáng", "get up", "bangun"],
    ["之前", "zhī qián", "", ""],
    ["回家", "huí jiā", "go home", "pulang rumah"],
    ["啊", "a", "", ""],
    ["！”", "", "", ""],
    ["鞋子们", "xié zi men", "The shoes", "Kasut-kasut"],
    ["吵嚷着", "chǎo rǎng zhe", "shouted", "bercakap riuh"],
    ["……", "", "", ""],
    ["快乐的", "kuài lè de", "Joyful", "Gembira"],
    ["游行", "yóu xíng", "parade", "perarakan"],
    ["变成", "biàn chéng", "became", "menjadi"],
    ["了", "le", "", ""],
    ["惊恐万状", "jīng kǒng wàn zhuàng", "panic-stricken", "kecoh"],
    ["的混乱", "de hùn luàn", "chaos", "kekacauan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    ["乱了方寸", "luàn le fāng cùn", "Panicked", "Hilang arah"],
    ["的鞋", "de xié", "shoes", "kasut-kasut"],
    ["顿时", "dùn shí", "immediately", "serta-merta"],
    ["都", "dōu", "all", "semua"],
    ["迷了路", "mí le lù", "got lost", "sesat"],
    ["。", "", "", ""],
    ["太阳", "tài yáng", "The sun", "Matahari"],
    ["升高时", "shēng gāo shí", "when it rose higher", "apabila naik tinggi"],
    ["，", "", "", ""],
    ["它们", "tā men", "they", "mereka"],
    ["还在", "hái zài", "still", "masih"],
    ["街上", "jiē shàng", "on the street", "di jalan"],
    ["跌跌撞撞地", "diē diē zhuàng zhuàng de", "stumbling", "terhuyung-hayang"],
    ["走着", "zǒu zhe", "walking", "berjalan"],
    ["……", "", "", ""],
    ["球鞋", "qiú xié", "Sneakers", "Kasut sukan"],
    ["被", "bèi", "were", "telah"],
    ["自己的鞋带", "zì jǐ de xié dài", "their own laces", "tali sendiri"],
    ["绊倒了", "bàn dǎo le", "tripped", "tersandung"],
    ["，", "", "", ""],
    ["鞋跟儿", "xié gēn r", "Heels", "Tumit kasut"],
    ["踏着了", "tà zháo le", "stepped on", "memijak"],
    ["鞋尖儿", "xié jiān r", "toes", "hujung kasut"],
    ["，", "", "", ""],
    ["有些鞋带", "yǒu xiē xié dài", "Some laces", "Sesetengah tali kasut"],
    ["还", "hái", "even", "malah"],
    ["纠缠在", "jiū chán zài", "tangled", "terbelit"],
    ["一起了", "yī qǐ le", "together", "bersama"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    ["太阳", "tài yáng", "The sun", "Matahari"],
    ["越升越高", "yuè shēng yuè gāo", "rose higher and higher", "semakin naik"],
    ["，", "", "", ""],
    ["鞋子们", "xié zi men", "the shoes", "kasut-kasut"],
    ["仍在", "réng zài", "still", "masih"],
    ["街上", "jiē shàng", "on the street", "di jalan"],
    ["马不停蹄地", "mǎ bù tíng tí de", "non-stop", "tanpa henti"],
    ["奔着", "bēn zhe", "rushing", "berlari"],
    ["，", "", "", ""],
    ["同时", "tóng shí", "and at the same time", "sementara"],
    ["大呼小叫", "dà hū xiǎo jiào", "shouting", "berseru-seru"],
    ["。", "", "", ""],
    ["许多鞋", "xǔ duō xié", "Many shoes", "Banyak kasut"],
    ["爬进", "pá jìn", "crawled into", "merangkak masuk ke"],
    ["自己", "zì jǐ", "their own", "diri sendiri"],
    ["所能看到", "suǒ néng kàn dào", "the first", "yang dapat dilihat"],
    ["的第一扇", "de dì yī shàn", "first", "pertama"],
    ["窗户", "chuāng hu", "window", "tingkap"],
    ["，", "", "", ""],
    ["把", "bǎ", "", ""],
    ["自己", "zì jǐ", "themselves", "diri sendiri"],
    ["安顿在", "ān dùn zài", "settled under", "menempatkan di"],
    ["所能找到的", "suǒ néng zhǎo dào de", "the first", "yang dapat ditemui"],
    ["第一张", "dì yī zhāng", "first", "pertama"],
    ["床下", "chuáng xià", "bed", "katil"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第9段

    ["爸爸", "bà ba", "Dad", "Ayah"],
    ["起床后", "qǐ chuáng hòu", "After getting up", "Selepas bangun"],
    ["，", "", "", ""],
    ["在", "zài", "under", "di"],
    ["床底下", "chuáng dǐ xià", "the bed", "bawah katil"],
    ["发现了", "fā xiàn le", "found", "menemui"],
    ["一只", "yì zhī", "a", "sehelai"],
    ["大婶的", "dà shěn de", "auntie's", "makcik punya"],
    ["浅口无带皮鞋", "qiǎn kǒu wú dài pí xié", "slip-on leather shoe", "kasut kulit tanpa tali"],
    ["、", "", "", ""],
    ["一只", "yì zhī", "a", "sehelai"],
    ["蓝色的", "lán sè de", "blue", "biru"],
    ["休闲鞋", "xiū xián xié", "casual shoe", "kasut santai"],
    ["、", "", "", ""],
    ["一只", "yì zhī", "a", "sehelai"],
    ["左脚拖鞋", "zuǒ jiǎo tuō xié", "left slipper", "selipar kiri"],
    ["，", "", "", ""],
    ["还有", "hái yǒu", "and also", "dan juga"],
    ["一只", "yì zhī", "a", "sehelai"],
    ["男孩儿的", "nán hái r de", "boy's", "budak lelaki punya"],
    ["右脚鞋", "yòu jiǎo xié", "right shoe", "kasut kanan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第10段

    ["“", "", "", ""],
    ["这到底……", "zhè dào dǐ……", "What in the world...", "Apakah ini..."],
    ["”", "", "", ""],
    ["爸爸说", "bà ba shuō", "Dad said", "Ayah berkata"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第11段

    ["“", "", "", ""],
    ["这到底……", "zhè dào dǐ……", "What in the world...", "Apakah ini..."],
    ["”", "", "", ""],
    ["全镇的人", "quán zhèn de rén", "The whole town", "Seluruh penduduk bandar"],
    ["起床后", "qǐ chuáng hòu", "after getting up", "selepas bangun"],
    ["都", "dōu", "all", "semua"],
    ["这么说", "zhè me shuō", "said the same", "berkata begitu"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第12段

    ["那天早晨", "nà tiān zǎo chén", "That morning", "Pagi itu"],
    ["，", "", "", ""],
    ["人们", "rén men", "people", "orang ramai"],
    ["只好", "zhǐ hǎo", "had to", "terpaksa"],
    ["一拐一拐地", "yì guǎi yì guǎi de", "limping", "terhincut-hincut"],
    ["去上班", "qù shàng bān", "go to work", "pergi bekerja"],
    ["、", "", "", ""],
    ["上学", "shàng xué", "go to school", "pergi sekolah"],
    ["，", "", "", ""],
    ["因", "yīn", "because", "kerana"],
    ["他们的鞋", "tā men de xié", "their shoes", "kasut mereka"],
    ["都", "dōu", "all", "semua"],
    ["不合脚", "bù hé jiǎo", "didn't fit", "tidak sesuai"],
    ["，", "", "", ""],
    ["不是", "bú shì", "either", "bukan"],
    ["太大", "tài dà", "too big", "terlalu besar"],
    ["就是", "jiù shì", "or", "atau"],
    ["太小", "tài xiǎo", "too small", "terlalu kecil"],
    ["，", "", "", ""],
    ["要不", "yào bù", "or", "atau"],
    ["就", "jiù", "were", "ialah"],
    ["都是右脚鞋", "dōu shì yòu jiǎo xié", "all right shoes", "semua kasut kanan"],
    ["，", "", "", ""],
    ["或", "huò", "or", "atau"],
    ["全都是", "quán dōu shì", "all", "semuanya"],
    ["左脚鞋", "zuǒ jiǎo xié", "left shoes", "kasut kiri"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第13段

    ["人们", "rén men", "People", "Orang ramai"],
    ["挠着头", "náo zhe tóu", "scratching their heads", "menggaru kepala"],
    ["相互问", "xiāng hù wèn", "asked each other", "saling bertanya"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我的鞋", "wǒ de xié", "My shoes", "Kasut saya"],
    ["在哪儿啊", "zài nǎ r a", "where are", "di mana"],
    ["？", "", "", ""],
    ["谁穿了", "shuí chuān le", "Who is wearing", "Siapa pakai"],
    ["我的鞋啊", "wǒ de xié a", "my shoes", "kasut saya"],
    ["？”", "", "", ""],
    ["大家", "dà jiā", "Everyone", "Semua orang"],
    ["相互查看", "xiāng hù chá kàn", "checked each other's", "saling memeriksa"],
    ["对方的脚", "duì fāng de jiǎo", "feet", "kaki orang lain"],
    ["，", "", "", ""],
    ["不时", "bù shí", "from time to time", "kadang-kadang"],
    ["听到", "tīng dào", "heard", "terdengar"],
    ["有人喊", "yǒu rén hǎn", "someone shouting", "ada orang berteriak"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["啊", "a", "Ah", "Ah"],
    ["，", "", "", ""],
    ["我的", "wǒ de", "my", "saya punya"],
    ["棕色左脚鞋", "zōng sè zuǒ jiǎo xié", "brown left shoe", "kasut kiri perang"],
    ["在那儿", "zài nà r", "is there", "di sana"],
    ["！”", "", "", ""],
    ["或者", "huò zhě", "or", "atau"],
    ["，", "", "", ""],
    ["“", "", "", ""],
    ["你穿的", "nǐ chuān de", "You are wearing", "Awak pakai"],
    ["是我的", "shì wǒ de", "my", "saya punya"],
    ["桃红色凉鞋", "táo hóng sè liáng xié", "pink sandals", "sandal merah jambu"],
    ["……”", "", "", ""],
    ["过了", "guò le", "After", "Selepas"],
    ["好一阵子", "hǎo yí zhèn zi", "a while", "seketika"],
    ["，", "", "", ""],
    ["人们", "rén men", "people", "orang ramai"],
    ["都", "dōu", "all", "semua"],
    ["找回了", "zhǎo huí le", "found back", "menemui semula"],
    ["自己的鞋", "zì jǐ de xié", "their own shoes", "kasut sendiri"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第14段

    ["只有", "zhǐ yǒu", "Only", "Hanya"],
    ["爸爸的", "bà ba de", "Dad's", "Ayah punya"],
    ["工夫", "gōng fu", "time", "masa"],
    ["长一些", "cháng yì xiē", "took longer", "lebih lama"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["他那", "tā nà", "his", "dia punya"],
    ["淘气的", "táo qì de", "naughty", "nakal"],
    ["左脚鞋", "zuǒ jiǎo xié", "left shoe", "kasut kiri"],
    ["爬到了", "pá dào le", "climbed onto", "memanjat ke"],
    ["一棵树上", "yì kē shù shàng", "a tree", "sebatang pokok"],
    ["，", "", "", ""],
    ["三天以后", "sān tiān yǐ hòu", "three days later", "tiga hari kemudian"],
    ["才", "cái", "only then", "baru"],
    ["被风刮到", "bèi fēng guā dào", "was blown down by the wind", "diterbangkan angin ke"],
    ["了地面", "le dì miàn", "the ground", "tanah"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["尤今", "yóu jīn", "You Jin", "You Jin"],
    ["《", "", "", ""],
    ["淘气的鞋", "táo qì de xié", "Naughty Shoes", "Kasut Nakal"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
